drop table if exists users;
create table users (
  id integer primary key autoincrement,
  facebook_id text,
  username text,
  score_9 integer default 0,
  score_10 integer default 0,
  score_11 integer default 0,
  score_14 integer default 0,
  score_15 integer default 0,
  score_17 integer default 0,
  score_18 integer default 0,
  score_21 integer default 0,
  score_22 integer default 0,
  score_23 integer default 0,
  score_24 integer default 0,
  score_25 integer default 0,
  count_9 integer default 0,
  count_10 integer default 0,
  count_11 integer default 0,
  count_14 integer default 0,
  count_15 integer default 0,
  count_17 integer default 0,
  count_18 integer default 0,
  count_21 integer default 0,
  count_22 integer default 0,
  count_23 integer default 0,
  count_24 integer default 0,
  count_25 integer default 0
);
